feat/owner assets path
thematters/traveloggers-app pull request #215
Opened 2021-12-01 01:27 UTC by tx0c

* 3d775fd add `/owner/[address].tsx` path
* c8cbe2a add getRecentLogs in the context

2021-12-02 01:21 UTC, tx0c commented on src/components/LogbookContext/index.tsx
> +  getOwnNFTs: (owner?: string | null | undefined) => Promise<void>
is @robertu7 aware of an address type?  to combine all `string | null | undefined` types?

2021-12-02 01:23 UTC, tx0c commented on src/components/LogbookContext/index.tsx
> +  const getOwnNFTs = async (owner: string | null | undefined = account) => {
an `address` type to be used here?

2021-12-02 03:33 UTC, robertu7 requested changes

2021-12-02 04:22 UTC, tx0c commented on src/components/LogbookContext/index.tsx
> +  const getRecentLogbooks = async (limit: number = 10) => {
yes, this is exported, and can be re-used

2021-12-02 05:38 UTC, tx0c commented on src/components/LogbookContext/index.tsx
> +  const getRecentLogbooks = async (limit: number = 10) => {
after #213 merged, this can be rebased and will be much cleaner

2021-12-03 03:12 UTC, robertu7 approved these changes

2021-12-04 09:47 UTC, merged